FROM node:22-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src

RUN mkdir -p /data/objects && chmod -R 777 /data

ENV NODE_ENV=production
ENV NODE_PORT=8081
ENV STORAGE_PATH=/data/objects

EXPOSE 8081

CMD ["npx", "tsx", "src/storage/index.ts"]
